default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.pgres[:username] %>
  password: <%= Rails.application.credentials.pgres[:password] %>


development:
  <<: *default
  database: book_store

test:
  <<: *default
  database: test_bookstore

production:
  <<: *default
  adapter: postgresql
  database: book_store_production
